<?php
require __DIR__.'/../custom/external_videos/lib/external_videos_lib.php';
$slug=$_GET['slug']??'';
$v=ev_get_by_slug($slug);
if(!$v||$v['status']!=='published'){http_response_code(404);echo 'Video unavailable';exit;}
ev_db()->query('UPDATE cb_external_videos SET view_count=view_count+1 WHERE id='.(int)$v['id']);
$canonical='http://'.($_SERVER['HTTP_HOST']??'162.35.166.53').'/external_video.php?slug='.rawurlencode($v['slug']);
$mediaUrl = trim((string)($v['download_url'] ?? ''));
$isHls = $mediaUrl !== '' && preg_match('~\.m3u8(?:\?|$)~i', parse_url($mediaUrl, PHP_URL_PATH) ?: '');
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=ev_h($v['title'])?></title><meta name="description" content="<?=ev_h(mb_substr(strip_tags($v['description']??''),0,155))?>"><link rel="canonical" href="<?=ev_h($canonical)?>"><link rel="stylesheet" href="/styles/cb_28/theme/css/portal.css?v=20260629"><link rel="stylesheet" href="/styles/cb_28/theme/css/external-videos.css?v=3"><style>.external-player video{width:100%;height:100%;background:#000;border:0;border-radius:14px}.external-player .fallback{padding:24px;background:#111;color:#fff;border-radius:14px}</style></head><body class="portal-shell"><nav class="oc-portal-nav" style="position:static"><a href="/">Home</a><a href="/external_feed.php">External Videos</a><a href="/videos.php">Hosted Videos</a><a href="/dmca.php">DMCA</a></nav><main class="external-watch"><div class="external-grid"><section><div class="external-player"><?php if($isHls): ?><video id="external-hls-player" controls playsinline preload="metadata" poster="<?=ev_h($v['thumbnail_url']??'')?>"></video><noscript><p class="fallback"><a rel="nofollow noopener noreferrer" href="<?=ev_h($mediaUrl)?>">Open video stream</a></p></noscript><?php else: ?><?=ev_iframe($v)?><?php endif; ?></div><h1><?=ev_h($v['title'])?></h1><div class="meta"><?=number_format((int)$v['view_count']+1)?> views · <?=ev_h($v['provider'])?> · <?=ev_h($v['created_at'])?> <?=((int)$v['is_18_plus']?' · 18+':'')?></div><p><?=nl2br(ev_h($v['description']))?></p><div class="chips"><?php foreach(array_filter(array_map('trim',explode(',',$v['tags']??''))) as $tag): ?><a href="/external_feed.php?q=<?=rawurlencode($tag)?>"><?=ev_h($tag)?></a><?php endforeach;?></div><p>Source: <a rel="nofollow noopener noreferrer" target="_blank" href="<?=ev_h($v['source_url'])?>"><?=ev_h(parse_url($v['source_url'],PHP_URL_HOST)?:$v['provider'])?></a></p><p class="actions"><a href="/report-abuse.php">Report</a> · <a href="/dmca.php">DMCA / Copyright Complaint</a> · <a href="/content-removal.php">Content Removal</a></p></section><aside><h2>Recommended</h2><?php foreach(ev_list(['published'=>1,'limit'=>8]) as $r): if($r['id']==$v['id'])continue; ?><p><a href="/external_video.php?slug=<?=rawurlencode($r['slug'])?>"><?=ev_h($r['title'])?></a></p><?php endforeach;?></aside></div></main><?php if($isHls): ?><script src="https://cdn.jsdelivr.net/npm/hls.js@1"></script><script>const src=<?=json_encode($mediaUrl, JSON_UNESCAPED_SLASHES)?>,v=document.getElementById('external-hls-player');if(v){if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=src}else if(window.Hls&&Hls.isSupported()){const h=new Hls({maxBufferLength:30});h.loadSource(src);h.attachMedia(v)}else{v.outerHTML='<p class="fallback"><a rel="nofollow noopener noreferrer" href="'+src+'">Open video stream</a></p>'}}</script><?php endif; ?><script src="/external_age_gate.js"></script></body></html>
