<?php
require __DIR__.'/../custom/external_videos/lib/external_videos_lib.php';

$q = trim((string)($_GET['q'] ?? ''));
$page = max(1, (int)($_GET['page'] ?? 1));
$perPage = 48;
$total = ev_count(['published' => 1, 'q' => $q]);
$totalPages = max(1, (int)ceil($total / $perPage));
if ($page > $totalPages) { $page = $totalPages; }
$offset = ($page - 1) * $perPage;
$items = ev_list(['published' => 1, 'q' => $q, 'limit' => $perPage, 'offset' => $offset]);
$baseParams = $q !== '' ? ['q' => $q] : [];
function ev_feed_page_url(int $page, array $baseParams): string { $params = $baseParams; if ($page > 1) { $params['page'] = $page; } $query = http_build_query($params); return '/external_feed.php' . ($query ? '?' . $query : ''); }
$title = $q !== '' ? 'Search results for “'.$q.'”' : 'External Videos';
$desc = $q !== '' ? 'Search published external videos for '.$q.'.' : 'Published external embed videos.';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=ev_h($title)?><?= $page > 1 ? ' - Page '.(int)$page : '' ?></title><meta name="description" content="<?=ev_h($desc)?>"><link rel="stylesheet" href="/styles/cb_28/theme/css/portal.css?v=20260629"><link rel="stylesheet" href="/styles/cb_28/theme/css/external-videos.css?v=4"></head><body class="portal-shell"><nav class="oc-portal-nav" style="position:static"><a href="/">Home</a><a href="/external_feed.php">External Videos</a><a href="/videos.php">Hosted Videos</a></nav><main><section class="ev-toolbar"><div><h1 class="ev-title"><?=ev_h($title)?></h1><p class="ev-count"><?=number_format($total)?> videos<?= $q !== '' ? ' found' : '' ?><?= $totalPages > 1 ? ' · page '.(int)$page.' of '.(int)$totalPages : '' ?></p></div><form class="ev-search" method="get" action="/external_feed.php"><input type="search" name="q" value="<?=ev_h($q)?>" placeholder="Search videos, tags, providers..." aria-label="Search videos"><button type="submit">Search</button><?php if($q !== ''): ?><a class="ev-clear" href="/external_feed.php">Clear</a><?php endif; ?></form></section><?php if($items): ?><div class="ev-grid"><?php foreach($items as $v): ?><article class="ev-card"><a href="/external_video.php?slug=<?=rawurlencode($v['slug'])?>"><img src="<?=ev_h($v['thumbnail_url'])?>" alt="<?=ev_h($v['title'])?>" loading="lazy"><h3><?=ev_h($v['title'])?></h3><div class="ev-meta"><?=number_format((int)$v['view_count'])?> views · <?=ev_h($v['provider'])?> <?=((int)$v['is_18_plus']?' · 18+':'')?></div></a></article><?php endforeach;?></div><?php else: ?><div class="ev-empty"><h2>No videos found</h2><p>Try a different keyword or clear the search.</p></div><?php endif; ?><?php if($totalPages > 1): ?><nav class="ev-pagination" aria-label="Video pagination"><?php if($page > 1): ?><a href="<?=ev_h(ev_feed_page_url($page-1,$baseParams))?>">‹ Previous</a><?php endif; ?><?php $start=max(1,$page-2); $end=min($totalPages,$page+2); if($start>1): ?><a href="<?=ev_h(ev_feed_page_url(1,$baseParams))?>">1</a><?php if($start>2): ?><span>…</span><?php endif; endif; ?><?php for($i=$start;$i<=$end;$i++): ?><?php if($i===$page): ?><span class="active"><?=$i?></span><?php else: ?><a href="<?=ev_h(ev_feed_page_url($i,$baseParams))?>"><?=$i?></a><?php endif; ?><?php endfor; ?><?php if($end<$totalPages): ?><?php if($end<$totalPages-1): ?><span>…</span><?php endif; ?><a href="<?=ev_h(ev_feed_page_url($totalPages,$baseParams))?>"><?=$totalPages?></a><?php endif; ?><?php if($page < $totalPages): ?><a href="<?=ev_h(ev_feed_page_url($page+1,$baseParams))?>">Next ›</a><?php endif; ?></nav><?php endif; ?></main></body></html>
