<?php
if (!defined('EXTERNAL_VIDEOS_LIB')) { define('EXTERNAL_VIDEOS_LIB', true);
function ev_db(): mysqli { static $db=null; if($db instanceof mysqli)return $db; require __DIR__.'/../../../upload/includes/config.php'; $db=new mysqli($DBHOST,$DBUSER,$DBPASS,$DBNAME,(int)$DBPORT); if($db->connect_errno){http_response_code(500);die('Database unavailable');} $db->set_charset('utf8mb4'); return $db; }
function ev_h($s): string { return htmlspecialchars((string)$s, ENT_QUOTES|ENT_SUBSTITUTE, 'UTF-8'); }
function ev_slugify(string $s): string { $s=strtolower(trim($s)); $s=preg_replace('/[^a-z0-9]+/i','-',$s); $s=trim($s,'-'); return $s ?: 'external-video-'.time(); }
function ev_safe_url(string $url): bool { $p=parse_url($url); return (bool)($p && !empty($p['scheme']) && !empty($p['host']) && in_array(strtolower($p['scheme']),['http','https'],true)); }
function ev_allowed_embed(string $url): array { if(!ev_safe_url($url)) return [false,'Only http/https URLs are allowed']; $host=strtolower(parse_url($url,PHP_URL_HOST)?:''); $rs=ev_db()->query('SELECT provider,domain FROM cb_external_video_providers WHERE is_active=1'); while($r=$rs->fetch_assoc()){ $d=strtolower($r['domain']); if($host===$d || str_ends_with($host,'.'.$d)) return [true,$r['provider']]; } return [false,'Embed domain is not whitelisted: '.$host]; }
function ev_unique_slug(string $title, ?int $exclude=null): string { $db=ev_db(); $base=ev_slugify($title); $slug=$base; $i=2; while(true){ $sql='SELECT id FROM cb_external_videos WHERE slug=?'.($exclude?' AND id<>?':'').' LIMIT 1'; $st=$db->prepare($sql); if($exclude)$st->bind_param('si',$slug,$exclude); else $st->bind_param('s',$slug); $st->execute(); $r=$st->get_result()->fetch_assoc(); $st->close(); if(!$r)return $slug; $slug=$base.'-'.$i++; } }
function ev_detect_provider(string $url): string { $h=strtolower(parse_url($url,PHP_URL_HOST)?:''); $h=preg_replace('/^www\./','',$h); if(str_contains($h,'youtube')||$h==='youtu.be')return 'youtube'; if(str_contains($h,'vimeo'))return 'vimeo'; return $h?:'external'; }
function ev_to_embed_url(string $url): string { if(!ev_safe_url($url))return ''; $h=strtolower(parse_url($url,PHP_URL_HOST)?:''); $h=preg_replace('/^www\./','',$h); $path=trim(parse_url($url,PHP_URL_PATH)?:'','/'); parse_str(parse_url($url,PHP_URL_QUERY)?:'', $q); if($h==='youtu.be'&&$path)return 'https://www.youtube-nocookie.com/embed/'.rawurlencode(explode('/',$path)[0]); if(str_contains($h,'youtube')&&!empty($q['v']))return 'https://www.youtube-nocookie.com/embed/'.rawurlencode($q['v']); if($h==='player.vimeo.com')return $url; if(str_contains($h,'vimeo')&&preg_match('/(\d+)/',$path,$m))return 'https://player.vimeo.com/video/'.$m[1]; return $url; }
function ev_import_metadata(string $url): array { $embed=ev_to_embed_url($url); $provider=ev_detect_provider($url); $id=basename(parse_url($embed,PHP_URL_PATH)?:''); return ['title'=>ucfirst($provider).' External Video '.$id,'slug'=>'','description'=>'Imported external embed video pending review.','thumbnail_url'=>$provider==='youtube'&&$id?'https://img.youtube.com/vi/'.rawurlencode($id).'/hqdefault.jpg':'','source_url'=>$url,'embed_url'=>$embed,'download_url'=>'','provider'=>$provider,'author'=>'','duration'=>'','tags'=>'external, imported','category_id'=>'','status'=>'pending','is_18_plus'=>1,'source_license'=>'','review_note'=>'','authorized_download'=>0,'download_status'=>'none']; }
function ev_allowed_status(string $s): string { return in_array($s,['pending','published','rejected','broken','removed'],true)?$s:'pending'; }
function ev_allowed_download_status(string $s): string { return in_array($s,['none','queued','downloading','downloaded','imported','failed'],true)?$s:'none'; }
function ev_upsert(array $d): array { $db=ev_db(); $title=trim($d['title']??''); if($title==='')return [false,'Title required']; $source=trim($d['source_url']??''); $embed=trim($d['embed_url']??''); if(!ev_safe_url($source))return [false,'Invalid source_url']; [$ok,$prov]=ev_allowed_embed($embed); if(!$ok)return [false,$prov]; $download=trim($d['download_url']??''); if($download!=='' && !ev_safe_url($download))return [false,'Invalid download_url']; $provider=trim($d['provider']??'')?:$prov; $status=ev_allowed_status($d['status']??'pending'); $is18=isset($d['is_18_plus'])?(int)!!$d['is_18_plus']:1; $id=(int)($d['id']??0); $slug=trim($d['slug']??'')?:ev_unique_slug($title,$id?:null); $desc=$d['description']??''; $thumb=$d['thumbnail_url']??''; $author=$d['author']??''; $duration=($d['duration']??'')===''?null:(int)$d['duration']; $tags=$d['tags']??''; $cat=($d['category_id']??'')===''?null:(int)$d['category_id']; $lic=$d['source_license']??''; $note=$d['review_note']??''; if($id){ $st=$db->prepare('UPDATE cb_external_videos SET title=?,slug=?,description=?,thumbnail_url=?,source_url=?,embed_url=?,download_url=?,provider=?,author=?,duration=?,tags=?,category_id=?,status=?,is_18_plus=?,source_license=?,review_note=?,updated_at=NOW() WHERE id=?'); $st->bind_param('sssssssssisisissi',$title,$slug,$desc,$thumb,$source,$embed,$download,$provider,$author,$duration,$tags,$cat,$status,$is18,$lic,$note,$id); } else { $st=$db->prepare('INSERT INTO cb_external_videos (title,slug,description,thumbnail_url,source_url,embed_url,download_url,provider,author,duration,tags,category_id,status,is_18_plus,source_license,review_note,authorized_download,download_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,\'none\') ON DUPLICATE KEY UPDATE title=VALUES(title),description=VALUES(description),thumbnail_url=VALUES(thumbnail_url),embed_url=VALUES(embed_url),download_url=VALUES(download_url),provider=VALUES(provider),author=VALUES(author),duration=VALUES(duration),tags=VALUES(tags),category_id=VALUES(category_id),updated_at=NOW()'); $st->bind_param('sssssssssisisiss',$title,$slug,$desc,$thumb,$source,$embed,$download,$provider,$author,$duration,$tags,$cat,$status,$is18,$lic,$note); } if(!$st->execute())return [false,$st->error]; return [true,$id?:($db->insert_id?:0)]; }
function ev_get(int $id): ?array { $st=ev_db()->prepare('SELECT * FROM cb_external_videos WHERE id=? LIMIT 1'); $st->bind_param('i',$id); $st->execute(); $r=$st->get_result()->fetch_assoc(); $st->close(); return $r?:null; }
function ev_get_by_slug(string $slug): ?array { $st=ev_db()->prepare('SELECT * FROM cb_external_videos WHERE slug=? LIMIT 1'); $st->bind_param('s',$slug); $st->execute(); $r=$st->get_result()->fetch_assoc(); $st->close(); return $r?:null; }
function ev_list(array $o=[]): array { $db=ev_db(); $w=[];$p=[];$t=''; if(!empty($o['published']))$w[]="status='published'"; if(!empty($o['q'])){$w[]='(title LIKE ? OR description LIKE ? OR tags LIKE ? OR provider LIKE ? OR source_url LIKE ?)';$q='%'.$o['q'].'%';array_push($p,$q,$q,$q,$q,$q);$t.='sssss';} if(!empty($o['status'])){$w[]='status=?';$p[]=$o['status'];$t.='s';} if(!empty($o['provider'])){$w[]='provider=?';$p[]=$o['provider'];$t.='s';} if(!empty($o['download_status'])){$w[]='download_status=?';$p[]=$o['download_status'];$t.='s';} $lim=max(1,min(200,(int)($o['limit']??24))); $sql='SELECT * FROM cb_external_videos '.($w?'WHERE '.implode(' AND ',$w):'').' ORDER BY created_at DESC LIMIT '.$lim; $st=$db->prepare($sql); if($p)$st->bind_param($t,...$p); $st->execute(); return $st->get_result()->fetch_all(MYSQLI_ASSOC); }
function ev_review_user_id(): int { if(class_exists('User')){ try { return (int)(User::getInstance()->getCurrentUserID() ?: 0); } catch(Throwable $e){} } return 0; }
function ev_mark_authorized(int $id, string $license, string $note, int $reviewedBy=0): array { $v=ev_get($id); if(!$v)return [false,'Video not found']; if(in_array($v['status'],['rejected','broken','removed'],true))return [false,'Rejected, broken, or removed videos cannot be authorized for download']; $reviewedBy=$reviewedBy?:ev_review_user_id(); $st=ev_db()->prepare('UPDATE cb_external_videos SET authorized_download=1, source_license=?, review_note=?, reviewed_by=?, reviewed_at=NOW(), updated_at=NOW() WHERE id=?'); $st->bind_param('ssii',$license,$note,$reviewedBy,$id); return $st->execute()?[true,'Authorized for download']:[false,$st->error]; }
function ev_queue_download(int $id, int $reviewedBy=0): array { $v=ev_get($id); if(!$v)return [false,'Video not found']; if((int)$v['authorized_download']!==1)return [false,'authorized_download=true is required before queueing']; if(in_array($v['status'],['rejected','broken','removed'],true))return [false,'Rejected, broken, or removed videos cannot be downloaded']; $reviewedBy=$reviewedBy?:ev_review_user_id(); $st=ev_db()->prepare("UPDATE cb_external_videos SET download_status='queued', download_error=NULL, reviewed_by=IFNULL(NULLIF(reviewed_by,0),?), reviewed_at=IFNULL(reviewed_at,NOW()), updated_at=NOW() WHERE id=?"); $st->bind_param('ii',$reviewedBy,$id); return $st->execute()?[true,'Queued for background download']:[false,$st->error]; }
function ev_set_status(int $id, string $status, string $note=''): array { $status=ev_allowed_status($status); $v=ev_get($id); if(!$v)return [false,'Video not found']; $st=ev_db()->prepare('UPDATE cb_external_videos SET status=?, review_note=IF(?<>\'\',?,review_note), reviewed_by=?, reviewed_at=NOW(), updated_at=NOW() WHERE id=?'); $uid=ev_review_user_id(); $st->bind_param('sssii',$status,$note,$note,$uid,$id); return $st->execute()?[true,'Status updated']:[false,$st->error]; }
function ev_iframe(array $v): string { return '<iframe src="'.ev_h($v['embed_url']).'" title="'.ev_h($v['title']).'" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen referrerpolicy="strict-origin-when-cross-origin" sandbox="allow-scripts allow-same-origin allow-presentation allow-popups"></iframe>'; }
function ev_local_watch_url(array $v): string { return !empty($v['clipbucket_video_id']) ? '/watch_video.php?v='.(int)$v['clipbucket_video_id'] : ''; }
}
